### ISSUE TITLE
Style geolocation popup

### ISSUE THREAD

**Issue by bl2i4n** [tjwoon/csAR#2]
I was wondering if there is a way to style the component that shows the geolocation on the camera overlay. 
Where is the styling found for this component?

Example:
```
geoLocations: [
{
  latitude: 1.2345,
  longitude: 101.2345678,
  name: "Location name"
}
```

I was able to get this to come up on our test app but we would like to style the popup better to better match my apps layout. Please let me know if this is possible!

Thanks!

**Comment by ShaliniShanmugam7** [comment]
Yes it is possible. Add your styled popup background images here `cordova-plugin-ar/src/ios/ARKit/Images` and rename the image values in **MarkerView.m** this file under Plugins folder.
